Tasks/urls.py
from django.urls import path
from Tasks import views

app_name = "Tasks"

urlpatterns = [
    path('', views.taskslist, name='TasksList'),
    path('create/', views.createtask, name='CreateTask'),
    path('delete/<int:pk>/', views.deletetask, name='DeleteTask'),
    path('update/<int:pk>/', views.updatetask, name='UpdateTask'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Tasks.urls'))
]

Tasks/models.py
from django.db import models

class Task(models.Model):
    titre = models.CharField(max_length=120)
    description = models.TextField(blank=True, null=True)
    is_finished = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Task"
        verbose_name_plural = "Tasks"
    
    def __str__(self):
        return self.titre

Tasks/forms.py
from django.forms import ModelForm
from .models import Task

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['titre', 'description']

Tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Task
from .forms import TaskForm

def taskslist(request):
    tasks = Task.objects.all()
    return render(request, "Tasks/list.html", {"tasks": tasks})

def createtask(request):
    form = TaskForm(request.POST or None)
    if form.is_valid():
        task = form.save()
        return redirect("Tasks:TasksList")
    return render(request, "Tasks/formulaire.html", {"form": form})

def deletetask(request, pk):
    task = Task.objects.get(id=pk)
    task.delete()
    return redirect("Tasks:TasksList")

def updatetask(request, pk):
    task = get_object_or_404(Task, id=pk)
    form = TaskForm(request.POST or None, instance=task)
    if form.is_valid():
        form.save()
        return redirect("Tasks:TasksList")
    return render(request, "Tasks/formulaire.html", {"form": form})

templates/Tasks/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
</head>
<body>
    {% block contents %}
    {% endblock contents %}
</body>
</html>

templates/Tasks/formulaire.html
{% extends 'Tasks/base.html' %}

{% block title %}Formulaire{% endblock title %}

{% block contents %}
<form method="POST">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Ajouter</button>
</form>
{% endblock contents %}

templates/Tasks/list.html
{% extends 'Tasks/base.html' %}

{% block title %}Liste des tâches à faire{% endblock title %}

{% block contents %}
<h1>Liste des tâches :</h1>
<a href="{% url 'Tasks:CreateTask' %}">Créer</a>
{% for task in tasks %}
<p>{{ forloop.counter }} | {{ task.titre }}</p>
<a href="{% url 'Tasks:UpdateTask' task.id %}">Modifier</a>
<a href="{% url 'Tasks:DeleteTask' task.id %}">Supprimer</a>
{% endfor %}
{% endblock contents %}